AllCops:
    DisplayCopNames: true
Style/Documentation:
    Enabled: false
Style/AsciiComments:
    Enabled: false
Style/StringLiterals:
    Enabled: false
Style/NumericLiterals:
    Enabled: false
Style/FrozenStringLiteralComment:
    Enabled: false
Layout/SpaceAroundEqualsInParameterDefault:
    EnforcedStyle: no_space
Layout/SpaceInsideHashLiteralBraces:
    EnforcedStyle: no_space
Metrics/LineLength:
    Max: 80
Metrics/MethodLength:
    Max: 20
Metrics/ClassLength:
    Max: 150