include_recipe './cookbooks/symboliclinks/default.rb'
include_recipe './cookbooks/bash/default.rb'
include_recipe './cookbooks/homebrew/default.rb'
include_recipe './cookbooks/powerline/default.rb'
include_recipe './cookbooks/fish/default.rb'
include_recipe './cookbooks/ruby/default.rb'
include_recipe './cookbooks/nvm/default.rb'
include_recipe './cookbooks/readline/default.rb'
include_recipe './cookbooks/git/default.rb'
include_recipe './cookbooks/tig/default.rb'
include_recipe './cookbooks/tmux/default.rb'
include_recipe './cookbooks/vim/default.rb'
include_recipe './cookbooks/vscode/default.rb'
include_recipe './cookbooks/apex/default.rb'
include_recipe './cookbooks/Xresources/default.rb'
include_recipe './cookbooks/macos/default.rb'

execute 'echo *********** all done. ***********'
